site_name: OneBot 12 QQ 扩展草案
repo_name: Sclock/onebot-qq-extension
repo_url: https://github.com/Sclock/onebot-qq-extension
docs_dir: specs

theme:
  name: material
  custom_dir: theme
  language: 'zh'
  logo: assets/images/logo-white.png
  favicon: assets/images/logo.png
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.sections
    - navigation.tabs

extra:
  search:
    language: 'jp' # 不支持中文，改成日文好像能搜到一部分中文了（无语）
  analytics:
    provider: google
    property: G-RT0B6ZLNQH

nav:
  - 介绍: index.md
  - 接口定义:
      - 概述: interface/index.md
      - 消息接口: interface/message.md
      - 单用户接口（Private / Direct）:
          - 用户消息事件: interface/user/message-events.md
          - 用户通知事件: interface/user/notice-events.md
          - 用户动作: interface/user/actions.md
      - 单级群组接口（Group）:
          - 群消息事件: interface/group/message-events.md
          - 群通知事件: interface/group/notice-events.md
          - 群动作: interface/group/actions.md
      - 两级群组接口（Guild-Channel）:
          - 群组消息事件: interface/guild/message-events.md
          - 群组通知事件: interface/guild/notice-events.md
          - 群组动作: interface/guild/actions.md
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
